sudo: required
services:
  - docker

before_install:
  - docker build -t prashanthsuresh/docker-react -f Dockerfile.dev .

script:
  - docker run prashanthsuresh/docker-react npm run test -- --coverage